duck_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: duckdb
      threads: 24
duck_dbt:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
